### ISSUE TITLE
Cloud: copy/paste not working.

### ISSUE THREAD

**Issue by alaindebecker** [newmips/newmips#21]
**Reproduce:** 
- Open a newMips app on the cloud
- list an entity, and display any of them in order to update it
- select a field and copy it with Ctrl-C or with the right-click menu
- select an other field on the same entity or an other entity and paste it with Ctrl-V or the right-click menu.

**Result**: nothing happens. 

**Expected result**: the first field gets copied.

**Comment by annelvk** [comment]
On a list of entities, this is not allowed to copy / paste data.
This is also not allowed to change values : you have to select "update" function to edit the selected entity.

It could be possible to add a new feature in a next release, but it is necessary to define the purpose.

Do you mean " select data " and add them to the clipboard ? Then it could be possible to paste values on any other field on a form ( update page or create page ).
Do you mean 'copy field value" and paste it to anoher field in the list ? click on "save" to apply your change or apply the change automatically ?

Feel free to explain us what is your need so that we could improve the software.

**Comment by alaindebecker** [comment]
I updated my question to change display with update.
Nevertheless, the copy paste works now.

**Comment by alaindebecker** [comment]
I edited my question to change display by modify/update.
Any way, by one of the great mysteries in computer science, it works now,
