### ISSUE TITLE
Bug in "one to one" relationship

### ISSUE THREAD

**Issue by alaindebecker** [newmips/newmips#23]
Using the Team-Player example of your doc does not seams to work : when creating a Player, you are not able to select the Player-Team from the Team entities.

Reproduce:
```
create entity Team
add field Team Name
create entity Member
add field Member Name
add field Team related to Member using Member Name
```
then
```
create a new Team entity with name : 'The Merry Hacker Company'
create a new Player entity with name 'AlainD', the try to select his team: 
a) The drop box is empty
b) Even if you type the name 'The Merry Hacker Company' in the team field, and press the save button, the Player is created but his team is not recorded properly, instead a player-name is used as the team-name. 
```

**Comment by Syno0** [comment]
Hello,

I think the problem is that you link your related to field with Member instead of Team, then when you try to connect a member to a team you can't find any team in the drop box.

Can you try again replacing this line:
`add field Team related to Member using Member Name`
with this line:
`add field Team related to Team using Team Name`

**Comment by alaindebecker** [comment]
Good spot. My mistake. 
Now AlainD is a member of the the Merry Hacker Company.
